#include <iostream>
int main(int argc, char* argv[]) {
    std::cout << "Example 01 from Chapter 03:" << std::endl;
    std::cout << "Running binary compiled from C++ code." << std::endl;
    std::cout << "Project files were generated by CMake." << std::endl;
    std::cout << "Project was built by Make." << std::endl;
    return 0;
}
